In [225]:
import pandas as pd
import numpy as np
import torch
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == 'experiments':
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))


In [226]:
df = pd.read_pickle('/Users/ballinliu/Desktop/PHD/Project1/cachedir/20260203_1522/data/outputs/ep0_stage_pv.pkl')
df['K'] = 1


In [227]:
import importlib
import experiments.fill_fullN_entrants as ffe
importlib.reload(ffe)



# 填充每个 path-branch 到 full_N
from experiments.fill_fullN_entrants import fill_df_to_fullN
import pandas as pd
import torch
from pathlib import Path

pkl_in = Path("/Users/ballinliu/Desktop/PHD/Project1/cachedir/20260203_1522/data/outputs/ep0_stage_pv.pkl")
pkl_out = Path("../cachedir/20260203_1522/data/outputs/ep0_stage_pv_full.pkl")
full_N = 1000

df = pd.read_pickle(pkl_in)
df['K'] = 1
df_filled = ffe.fill_df_to_fullN(df, full_N=full_N, device=torch.device("cpu"), entry_num=30)
pkl_out.parent.mkdir(parents=True, exist_ok=True)
df_filled.to_pickle(pkl_out)

print(f"filled df saved to {pkl_out}, added {len(df_filled) - len(df)} rows")


filled df saved to ../cachedir/20260203_1522/data/outputs/ep0_stage_pv_full.pkl, added 997002 rows


In [228]:
df_filled.sort_values(by=['path', 'ID', 'branch'], inplace=True)

In [229]:
df_filled.describe()

,path,branch,b,z,ETA,i,x,Hatcf,LnKF,M,Entry,K
count,999000.000000,999000.000000,666666.000000,666666.000000,666666.000000,6.666660e+05,666666.000000,666666.000000,666666.000000,666666.000000,666666.000000,666666.0
mean,166.000000,1.000000,0.001448,-0.000707,0.030306,2.498396e-01,-1.997467,-2.368816,1.184682,1.432953,0.030969,1.0
std,96.128434,0.816497,0.030899,0.825440,0.171428,1.442029e-01,0.038688,0.094801,0.105543,0.938463,0.173234,0.0
min,0.000000,0.000000,0.000000,-4.124426,0.000000,9.536743e-07,-2.104424,-2.617348,0.982089,0.106397,0.000000,1.0
25%,83.000000,0.000000,0.000000,-0.557797,0.000000,1.252222e-01,-2.023970,-2.432543,1.147288,0.768037,0.000000,1.0
50%,166.000000,1.000000,0.000000,-0.000767,0.000000,2.496089e-01,-1.997458,-2.373077,1.186007,1.218861,0.000000,1.0
75%,249.000000,2.000000,0.000000,0.556832,0.000000,3.747658e-01,-1.972860,-2.311525,1.220062,1.898741,0.000000,1.0
max,332.000000,2.000000,0.997255,3.791574,1.000000,4.999999e-01,-1.871553,-1.680016,4.627234,6.333671,1.000000,1.0


In [230]:
df_filled['ID'].nunique()

333000

In [231]:
df_filled[(df_filled['path'] == 0) & (df_filled['Entry'] == 1)]

,path,ID,t,branch,b,z,ETA,i,x,Hatcf,LnKF,M,Entry,K
3390,0,0063cb39ff074caba0daf8a8e6abfb73,t+1_0,1,0.0,-1.519573,0.0,0.302501,-1.982804,-2.427599,1.221104,0.651937,1.0,1.0
4329,0,00fd8cd8248e41228ab0202757f9ab69,t+1_1,2,0.0,0.633396,0.0,0.380358,-2.009157,-2.422737,1.221973,0.629669,1.0,1.0
4354,0,0440e45c77684af49ad31d547a963ac9,t+1_1,2,0.0,0.435582,0.0,0.475400,-2.009157,-2.422737,1.221973,0.629669,1.0,1.0
3284,0,05699a65d02b4ddbb2ab5b9937458e6c,t+1_0,1,0.0,-0.667734,0.0,0.312777,-1.982804,-2.427599,1.221104,0.651937,1.0,1.0
4055,0,11e38a7a91664a28b45d432c6f078692,t+1_1,2,0.0,0.022894,0.0,0.316398,-2.009157,-2.422737,1.221973,0.629669,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3261,0,e9c6428597a748c0822678ed378bd8cd,t+1_0,1,0.0,0.786221,0.0,0.357166,-1.982804,-2.427599,1.221104,0.651937,1.0,1.0
3859,0,eae3c8f544b143918d75b7b4e9b9e036,t+1_0,1,0.0,0.218356,0.0,0.380751,-1.982804,-2.427599,1.221104,0.651937,1.0,1.0
3670,0,ef5602b8e82b41c399ab8bee33b0e1a1,t+1_0,1,0.0,0.571462,0.0,0.447731,-1.982804,-2.427599,1.221104,0.651937,1.0,1.0
4518,0,f5519c776cd9497ca16c6a7300b652bb,t+1_1,2,0.0,0.956526,0.0,0.135276,-2.009157,-2.422737,1.221973,0.629669,1.0,1.0


In [362]:
parent = df_filled[df_filled.branch == 0].reset_index(drop=True)
child1 = df_filled[df_filled.branch == 1].reset_index(drop=True)
child2 = df_filled[df_filled.branch == 2].reset_index(drop=True)

In [363]:
# display parent child1 child2's shape 
print("Parent shape:", parent.shape)
print("Child1 shape:", child1.shape)
print("Child2 shape:", child2.shape)

Parent shape: (333000, 14)
Child1 shape: (333000, 14)
Child2 shape: (333000, 14)


In [364]:
df1 = pd.merge(parent, child1, on=['ID'], suffixes=('', '_child1'), how = 'outer')
df2 = pd.merge(df1, child2, on=['ID'], suffixes=('', '_child2'), how = 'outer')

In [365]:

df2 = df2.sort_values(
    ['path', 'b'],
    ascending=[True, True],
    na_position='last',      # NaN 放后面
    kind='mergesort',        # 稳定
).reset_index(drop=True)


In [366]:
df2

,path,ID,t,branch,b,z,ETA,i,x,Hatcf,...,b_child2,z_child2,ETA_child2,i_child2,x_child2,Hatcf_child2,LnKF_child2,M_child2,Entry_child2,K_child2
0,0,d5dd638aa0b0430cbe0ef235b565663f,t,0,0.257586,-0.295468,0.0,0.232873,-2.011293,-1.915573,...,0.257586,0.146284,0.0,0.097150,-2.009157,-2.422737,1.221973,0.629669,0.0,1.0
1,0,4fe971a755ac4ab68a4b2d3fb12c940b,t,0,0.681185,-0.598211,0.0,0.346988,-2.011293,-1.915573,...,0.681185,-0.321999,0.0,0.327308,-2.009157,-2.422737,1.221973,0.629669,0.0,1.0
2,0,001ebf045c83499e92bf009b153a8d86,t,0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,-1.319593,0.0,0.143222,-2.009157,-2.422737,1.221973,0.629669,0.0,1.0
3,0,003c387f7ea24d19bfde869d0454bb60,t,0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.360994,0.0,0.073577,-2.009157,-2.422737,1.221973,0.629669,0.0,1.0
4,0,003fd55d50ba49d4bec07a4f9bd663a4,t,0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.463877,0.0,0.304081,-2.009157,-2.422737,1.221973,0.629669,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332995,332,feaeaf3e7d694e0683463d356999b5f8,t,0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,-1.040491,0.0,0.376366,-2.018852,-2.403026,1.201801,1.014451,0.0,1.0
332996,332,ff0de6e2700c41308cc3e69fa42a4811,t,0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.558195,0.0,0.321115,-2.018852,-2.403026,1.201801,1.014451,0.0,1.0
332997,332,ff719e29361b45b8bf05b8c6c554862f,t,0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.018946,0.0,0.316161,-2.018852,-2.403026,1.201801,1.014451,0.0,1.0
332998,332,ff8df0bbd7dc40129055c74c695df829,t,0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.974710,0.0,0.178269,-2.018852,-2.403026,1.201801,1.014451,0.0,1.0


In [411]:

# Convert the relevant columns b,z,eta,i,x,K to a PyTorch tensor P_s for parent, with shape (path,N,6).
# path is number of paths, N is number of unique IDs in each path (choose the biggest one).
path_num = df2['path'].nunique()
N = df2.groupby('path')['ID'].nunique().max()
branch_num = 2  # number of children branches per parent
P_s = torch.zeros((path_num, N, 5), dtype=torch.float32)
K_parent = torch.ones((path_num, N, 1), dtype=torch.float32)

alive_mask = torch.zeros((path_num, N), dtype=torch.bool)
entry_mask = torch.zeros((path_num, N, branch_num), dtype=torch.bool)
for i, (path, group) in enumerate(df2.groupby('path')):
    vals = torch.tensor(group[['b', 'z', 'ETA', 'i', 'x']].to_numpy(dtype=np.float32))
    P_s[i, : len(group)] = vals
    K_parent[i, : len(group), 0] = torch.tensor(group['K'].to_numpy(dtype=np.float32))
    alive_mask[i, : len(group)] = torch.tensor(group['b'].notna().to_numpy(dtype=np.float32))
    entry_mask[i, : len(group), 0] = torch.tensor(group['Entry_child1'].to_numpy(dtype=np.float32))
    entry_mask[i, : len(group), 1] = torch.tensor(group['Entry_child2'].to_numpy(dtype=np.float32))





In [435]:

# Convert the relevant columns b,z,\eta,i,x to a PyTorch tensor Children_s for child1 and child2, with shape (path, N, branch_num, 5) and K tensor K_chilren for child1 and child2, with shape (path, N, 2branch_num, 1)
Children_s = torch.zeros((path_num, N, branch_num, 5), dtype=torch.float32)
K_children = torch.zeros((path_num, N, branch_num, 1), dtype=torch.float32)
for i, (path, group) in enumerate(df2.groupby('path')):
    vals_child1 = torch.tensor(group[['b_child1', 'z_child1', 'ETA_child1', 'i_child1', 'x_child1']].to_numpy(dtype=np.float32))
    vals_child2 = torch.tensor(group[['b_child2', 'z_child2', 'ETA_child2', 'i_child2', 'x_child2']].to_numpy(dtype=np.float32))
    Children_s[i, : len(group), 0, :] = vals_child1
    Children_s[i, : len(group), 1, :] = vals_child2
    K_children[i, : len(group), 0, 0] = torch.tensor(group['K_child1'].to_numpy(dtype=np.float32))
    K_children[i, : len(group), 1, 0] = torch.tensor(group['K_child2'].to_numpy(dtype=np.float32))

In [436]:
Children_s[:,:,:,0] = 0 # set b to 0 for children 

In [437]:

# make the P_s and Children_s [path,full_N,5] and [path, full_N, 2, 5] tensors, N is 2000 samples, the rows beyond df set to 0 and same to K_parent and K_children. if the original tensor is equal to full ones ,make the full tensor directly

if P_s.shape[1] == full_N:
    P_s_full = P_s
    K_parent_full = K_parent
    Children_s_full = Children_s
    K_children_full = K_children
else:
    P_s_full = torch.zeros((path_num, full_N, 5), dtype=torch.float32)
    P_s_full[:, :P_s.shape[1], :] = P_s
    K_parent_full = torch.zeros((path_num, full_N, 1), dtype=torch.float32)
    K_parent_full[:, :K_parent.shape[1], :] = K_parent

    Children_s_full = torch.zeros((path_num, full_N, 2, 5), dtype=torch.float32)
    Children_s_full[:, :Children_s.shape[1], :, :] = Children_s
    K_children_full = torch.zeros((path_num, full_N, 2, 1), dtype=torch.float32)
    K_children_full[:, :K_children.shape[1], :, :] = K_children

In [415]:

# define a function named compute_quantile_features to compute quantile features for b and z
def compute_quantile_features(b_vals, z_vals, quantiles):
    b_quantiles = torch.quantile(b_vals, quantiles)
    z_quantiles = torch.quantile(z_vals, quantiles)
    quantile_features = torch.cat([b_quantiles, z_quantiles], dim=0)
    return quantile_features

In [416]:
# make the input tensors for FC2 model which is FC2_input_parent, it is a (path_num, 201), the first 200 are 100 quantile of b and z distribution which are from each path get the parent features b and z and get their quantiles, the last one is x feature
FC2_input_parent = torch.zeros((path_num, 201), dtype=torch.float32)
for i in range(path_num):
    b_vals = P_s_full[i, alive_mask[i], 0]
    z_vals = P_s_full[i, alive_mask[i], 1]
    quantile_features = compute_quantile_features(b_vals, z_vals, quantiles=torch.linspace(0, 1, steps=100))
    x_feature = P_s_full[i, alive_mask[i], 4].mean().unsqueeze(0)  # Use mean x feature
    FC2_input_parent[i, :200] = quantile_features
    FC2_input_parent[i, 200] = x_feature


In [417]:
# FIXME: FC2_output broadcast misses branch dimension; spec children need per-branch macro proxy
# define  a torch model first and then put the FC2_input_parent into FC2model to get the output
class FC2Model(torch.nn.Module):
    def __init__(self):
        super(FC2Model, self).__init__()
        self.fc1 = torch.nn.Linear(201, 128)
        self.fc2 = torch.nn.Linear(128, 64)
        self.fc3 = torch.nn.Linear(64, 2)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

fc2_model = FC2Model()
fc2_output_parent = fc2_model(FC2_input_parent)  # Shape: (path_num, 1)


In [418]:
# FIXME: PV_input dims/fields differ from spec (should include fc2 c/K proxy and respect branch dims)
# broadcast fc2_output_parent to shape (path_num, full_N, 2) and multiply with alive_mask to get the final output tensor FC2_output_children
FC2_output_parent = fc2_output_parent.unsqueeze(1).expand(-1, full_N, -1) * alive_mask.unsqueeze(-1)  # Shape: (path_num, full_N, 2)

In [419]:
# concat (P_s_full,FC2_output_parent) to get the final input tensor PV_input with shape (path_num, full_N, 7)
PV_input = torch.cat((P_s_full, FC2_output_parent), dim=-1)

In [420]:
# define a simple feedforward neural network model,with input size 7 and output size 3, make sure the value of the first 2 dims of output is whether 1 or 0, and the last dim is a float number, make sure the model will not break the gradient flow
class PVModel(torch.nn.Module):
    def __init__(self):
        super(PVModel, self).__init__()
        self.fc1 = torch.nn.Linear(7, 128)
        self.fc2 = torch.nn.Linear(128, 64)
        self.fc3 = torch.nn.Linear(64, 3)

    def forward(self, x):
        h = torch.relu(self.fc1(x))
        h = torch.relu(self.fc2(h))
        logits = self.fc3(h)
        probs = torch.sigmoid(logits[..., :2])          # probabilities for first two dims
        hard_bits = (probs > 0.5).float()                # hard 0/1 values
        hard_bits = hard_bits + (probs - probs.detach()) # straight-through: keeps gradient from probs
        value = logits[..., 2:3]                        # last dim stays continuous
        return torch.cat([hard_bits, value], dim=-1)


In [421]:
# input the PV_input except the -3 element into PVModel to get the final output PV_output with shape (path_num, full_N, 3)
pv_model = PVModel()
PV_output = pv_model(PV_input)  # Shape: (path_num, full_N, 3)

In [422]:
# update the alive_mask based on PV_output
# expand alive_prob to match entry_mask shape (path_num, full_N, 2)
alive_prob = PV_output[..., 0].clamp(0, 1)
base_alive = alive_mask.float()           # (path_num, full_N, 1)
alive_prefix = torch.cumprod(alive_prob, dim=1)       # stays 1 until first zero per path/step/branch
updated_alive = base_alive * alive_prob               # broadcast to (path_num, full_N, 2)
# if element in updated_alive is nan, fill it with 0
updated_alive = torch.nan_to_num(updated_alive, nan=0.0)
updated_alive = updated_alive.unsqueeze(-1).expand(-1, -1, 2)
entry_flag = entry_mask.float()                         # (path_num, full_N, 2)
alive_mask = updated_alive + entry_flag

In [423]:
# compute real lnk and hatc, for parent. for each path, choose all alive parents and compute their lnk and hatc based on PV_output and PV_input. Y = torch.exp(x + z) * K Phi = (1 - self.phi) * (1 + torch.exp(x + z)) * K * bar_z I = bar_i * K * i - bar_z * K + self.delta * K C = Y - I - Phi and then lnK is sum of all alive parents'K and get log, well hatc is sum of all alive parents'C and divide sum of K and get log. which bar_z is the first dimision of PV_output, bar_i is the second dimension of PV_output, and self.phi and self.delta are some constants, set self.phi = 0.1 and self.delta = 0.05 for now. using tensor operations to compute them without for loop.

phi = 0.1
delta = 0.05
bar_z = PV_output[..., 0:1]  # Shape: (path_num, full_N, 1)
bar_i = PV_output[..., 1:2]  # Shape: (path_num, full_N, 1)
Y = torch.exp(PV_input[..., 4:5] + PV_input[..., 1:2]) * K_parent_full  # Shape: (path_num, full_N, 1)
Phi = (1 - phi) * (1 + torch.exp(PV_input[..., 1:2] + PV_input[..., 3:4])) * K_parent_full * bar_z  # Shape: (path_num, full_N, 1)
I = bar_i * K_parent_full * PV_input[..., 3:4] - bar_z * K_parent_full + delta * K_parent_full  # Shape: (path_num, full_N, 1)
C = torch.abs(Y - I - Phi)  # Shape: (path_num, full_N, 1)
masked_K = torch.where(
    updated_alive[...,0:1] > 0,
    K_parent_full,
    torch.zeros_like(K_parent_full)
)

lnk_parent = torch.log(masked_K.sum(dim=1) + 1e-8)

masked_C = torch.where(
    updated_alive[...,0:1] > 0,
    C,
    torch.zeros_like(C)
)

hatc_parent = torch.log(torch.sum(masked_C, dim=1) / (torch.sum(masked_K, dim=1) + 1e-8))  # Shape: (path_num, 1)



In [424]:
# compute loss of FC2 model as the mean squared error between lnk_parent and fc2_output_parent[..., 0] and hatc_parent and fc2_output_parent[..., 1]
loss_parent = torch.mean((lnk_parent - fc2_output_parent[..., 0:1])**2) + torch.mean((hatc_parent - fc2_output_parent[..., 1:])**2)

In [438]:
# update children_s_full based on alive_mask and PV_output, children_s_full[:,:,:,0] is set to PV_output[...,2] * P_s_full[:,:,2] +  P_s_full[:,:,0] * (1- P_s_full[:,:,2])

masked_b = torch.where(
    updated_alive[...,0] > 0,
    P_s_full[:,:,0],
    torch.zeros_like(P_s_full[:,:,0])
)
masked_bp = torch.where(
    updated_alive[...,0] > 0,
    PV_output[...,2],
    torch.zeros_like(PV_output[...,2])
)

Children_s_full[:,:,0,0] = (masked_bp * Children_s_full[:,:,0,2]  +  masked_b * (1- Children_s_full[:,:,0,2]))
Children_s_full[:,:,1,0] = (masked_bp * Children_s_full[:,:,1,2] +  masked_b * (1- Children_s_full[:,:,1,2] ))


In [439]:
Children_s_full

tensor([[[[ 2.5759e-01, -4.7439e-01,  0.0000e+00,  3.9500e-01, -1.9828e+00],
          [ 2.5759e-01,  1.4628e-01,  0.0000e+00,  9.7150e-02, -2.0092e+00]],

         [[ 0.0000e+00, -4.1971e-01,  0.0000e+00,  4.1548e-01, -1.9828e+00],
          [ 0.0000e+00, -3.2200e-01,  0.0000e+00,  3.2731e-01, -2.0092e+00]],

         [[ 0.0000e+00,  9.9672e-01,  0.0000e+00,  2.7044e-01, -1.9828e+00],
          [ 0.0000e+00, -1.3196e+00,  0.0000e+00,  1.4322e-01, -2.0092e+00]],

         ...,

         [[ 0.0000e+00,  6.7870e-01,  0.0000e+00,  3.3089e-01, -1.9828e+00],
          [ 0.0000e+00, -1.4408e-01,  0.0000e+00,  1.5434e-01, -2.0092e+00]],

         [[ 0.0000e+00,  2.0768e+00,  0.0000e+00,  4.5194e-01, -1.9828e+00],
          [ 0.0000e+00, -1.4150e+00,  0.0000e+00,  2.0708e-03, -2.0092e+00]],

         [[ 0.0000e+00,  6.3880e-01,  0.0000e+00,  2.7451e-01, -1.9828e+00],
          [ 0.0000e+00, -4.2802e-01,  0.0000e+00,  1.2034e-01, -2.0092e+00]]],


        [[[ 1.3451e-01, -1.3853e-01,  0.0000e+0

In [440]:
# make the input tensors for FC2 model which is FC2_input_children it is a (path_num, 2, 201), the first 200 are 100 quantile of b and z distribution which are from each path get the parent features b and z and get their quantiles, the last one is x feature
FC2_input_children = torch.zeros((path_num, 2, 201), dtype=torch.float32)
for i in range(path_num):
    for j in range(2):
        b_vals = Children_s_full[i, alive_mask[i,:,j].bool(), j, 0]
        z_vals = Children_s_full[i, alive_mask[i,:,j].bool(), j, 1]
        quantile_features = compute_quantile_features(b_vals, z_vals, quantiles=torch.linspace(0, 1, steps=100))
        x_feature = Children_s_full[i, alive_mask[i,:,j].bool(), j, 4].mean().unsqueeze(0)  # Use mean x feature
        FC2_input_children[i, j, :200] = quantile_features
        FC2_input_children[i, j, 200] = x_feature

In [441]:
FC2_input_children

tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  2.2210,  2.2968, -1.9828],
         [ 0.0000,  0.0000,  0.0000,  ...,  1.8611,  1.9827, -2.0092]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  1.3133,  1.3290, -1.9884],
         [ 0.0000,  0.0000,  0.0000,  ...,  1.4940,  1.5405, -1.9835]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  1.4746,  1.5547, -1.9679],
         [ 0.0000,  0.0000,  0.0000,  ...,  1.4089,  1.5154, -1.9786]],

        ...,

        [[ 0.0000,  0.0000,  0.0000,  ...,  1.5702,  1.6897, -1.9927],
         [ 0.0000,  0.0000,  0.0000,  ...,  1.4670,  1.4934, -1.9905]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  1.7315,  1.7819, -1.9448],
         [ 0.0000,  0.0000,  0.0000,  ...,  1.8015,  1.9659, -1.9544]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  1.2302,  1.3423, -2.0189],
         [ 0.0000,  0.0000,  0.0000,  ...,  1.4772,  1.5755, -2.0189]]],
       grad_fn=<CopySlices>)

In [442]:
#  put the FC2_input_children into FC2model to get the output
FC2_output_children1 = fc2_model(FC2_input_children)


In [443]:
FC2_output_children1

tensor([[[-0.1385, -0.0442],
         [-0.1121, -0.0428]],

        [[-0.1094, -0.0286],
         [-0.1116, -0.0464]],

        [[-0.1003, -0.0392],
         [-0.1232, -0.0698]],

        ...,

        [[-0.1144, -0.0547],
         [-0.1238, -0.0431]],

        [[-0.1174, -0.0320],
         [-0.1061, -0.0540]],

        [[-0.1199, -0.0520],
         [-0.1094, -0.0314]]], grad_fn=<ViewBackward0>)

In [444]:
# broadcast FC2_output_children to shape (path_num, full_N, 2) and multiply with alive_mask to get the final output tensor FC2_output_children
FC2_output_children = FC2_output_children1.unsqueeze(1).expand(-1, full_N, -1, -1) * alive_mask.unsqueeze(-1)

In [445]:
# concat (Children_s_full,FC2_output_children) to get the final input tensor CV_input with shape (path_num, full_N, 2, 7)
CV_input = torch.cat((Children_s_full, FC2_output_children), dim=-1)

In [446]:
# input the CV_input except the -3 element into PVModel to get the final output CV_output with shape (path_num, full_N, 3)
CV_output = pv_model(CV_input)

In [447]:
# update the alive_mask_children based on CV_output

alive_mask_children = alive_mask.clone()
# update the alive_mask_children based on CV_output
alive_prob_children = CV_output[..., 0].clamp(0, 1)
base_alive_children = alive_mask.float()           # (path_num, full_N, 1)
updated_alive_children = base_alive_children * alive_prob_children               # broadcast to (path_num, full_N, 2)
alive_mask_children = updated_alive_children.unsqueeze(-1)

In [448]:
# update K_children_full based on K_children_full and CV_output, for bari which is the second dimision of CV_output, if bari is 1, then K_children_full = K_children_full * (1 + G), else K_children_full = K_children_full ,G is 0.14, keep the gradient flow
G = 0.14
bari = CV_output[..., 1:2]  # Shape: (path_num, full_N, 1)
K_children_full = K_children_full * (1 + G * bari) 


In [449]:
K_children_full

tensor([[[[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         ...,

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]]],


        [[[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         ...,

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]]],


        [[[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         ...,

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]]],


        ...,


        [[[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         [[1.1400],
          [1.1400]],

         ...,

         [[1.1400],
          [1.1400

In [474]:
# compute real lnk and hatc, for children. for each path, choose all alive children and compute their lnk and hatc based on PV_output and PV_input. Y = torch.exp(x + z) * K Phi = (1 - self.phi) * (1 + torch.exp(x + z)) * K * bar_z I = bar_i * K * i - bar_z * K + self.delta * K C = Y - I - Phi and then lnK is sum of all alive parents'K and get log, well hatc is sum of all alive children's C and divide sum of K and get log. which bar_z is the first dimision of PV_output, bar_i is the second dimension of PV_output, and self.phi and self.delta are some constants, set self.phi = 0.1 and self.delta = 0.05 for now. using tensor operations to compute them without for loop.
phi = 0.1
delta = 0.05
bar_z_children = CV_output[..., 0:1]  # Shape: (path_num, full_N, 2, 1)
bar_i_children = CV_output[..., 1:2]  # Shape: (path_num, full_N, 2, 1)
Y = torch.exp(CV_input[..., 4:5] + CV_input[..., 1:2]) * K_children_full  # Shape: (path_num, full_N, 2, 1)
Phi = (1 - phi) * (1 + torch.exp(CV_input[..., 1:2] + CV_input[..., 3:4])) * K_children_full * bar_z_children  # Shape: (path_num, full_N, 2, 1)
I = bar_i_children * K_children_full * CV_input[..., 3:4] - bar_z_children * K_children_full + delta * K_children_full  # Shape: (path_num, full_N, 2, 1)
C = torch.abs(Y - I - Phi)  # Shape: (path_num, full_N, 2, 1)
lnk_children = torch.log(torch.sum(K_children_full * alive_mask_children[...,0:1], dim=1) + 1e-8)  # Shape: (path_num, 1)
hatc_children = torch.log(torch.sum(C * alive_mask_children[...,0:1], dim=1) / (torch.sum(K_children_full * alive_mask_children[...,0:1], dim=1) + 1e-8))  # Shape: (path_num, 1)

In [475]:
hatc_children

tensor([[[ 0.8258],
         [ 0.6437]],

        [[ 0.5679],
         [ 0.4231]],

        [[ 0.3833],
         [ 0.2840]],

        [[ 0.7299],
         [ 0.7515]],

        [[ 0.4012],
         [ 0.8004]],

        [[ 0.6930],
         [ 0.4240]],

        [[ 0.2838],
         [ 0.2935]],

        [[ 0.6621],
         [ 0.3771]],

        [[ 0.5614],
         [ 0.4826]],

        [[ 0.6504],
         [ 0.2478]],

        [[ 0.4647],
         [ 0.4068]],

        [[ 0.1017],
         [ 0.4513]],

        [[ 0.6334],
         [ 0.4322]],

        [[ 0.4822],
         [ 0.5308]],

        [[ 0.6757],
         [ 0.5032]],

        [[ 0.5753],
         [ 0.5412]],

        [[ 0.7225],
         [ 0.5229]],

        [[ 0.4825],
         [ 0.5817]],

        [[ 0.7321],
         [ 0.4975]],

        [[ 0.3153],
         [ 0.1753]],

        [[ 0.6308],
         [ 0.1362]],

        [[ 0.2039],
         [ 0.6296]],

        [[ 0.6349],
         [ 0.4252]],

        [[ 0.4524],
         [ 0.5

In [476]:
# compute loss of FC2 model as the mean squared error between lnk_children and FC2_output_children1[..., 0] and hatc_children and FC2_output_children1[..., 1]
loss_children = torch.mean((lnk_children - FC2_output_children1[..., 0:1])**2) + torch.mean((hatc_children - FC2_output_children1[..., 1:])**2) 

In [477]:
hatc_children

tensor([[[ 0.8258],
         [ 0.6437]],

        [[ 0.5679],
         [ 0.4231]],

        [[ 0.3833],
         [ 0.2840]],

        [[ 0.7299],
         [ 0.7515]],

        [[ 0.4012],
         [ 0.8004]],

        [[ 0.6930],
         [ 0.4240]],

        [[ 0.2838],
         [ 0.2935]],

        [[ 0.6621],
         [ 0.3771]],

        [[ 0.5614],
         [ 0.4826]],

        [[ 0.6504],
         [ 0.2478]],

        [[ 0.4647],
         [ 0.4068]],

        [[ 0.1017],
         [ 0.4513]],

        [[ 0.6334],
         [ 0.4322]],

        [[ 0.4822],
         [ 0.5308]],

        [[ 0.6757],
         [ 0.5032]],

        [[ 0.5753],
         [ 0.5412]],

        [[ 0.7225],
         [ 0.5229]],

        [[ 0.4825],
         [ 0.5817]],

        [[ 0.7321],
         [ 0.4975]],

        [[ 0.3153],
         [ 0.1753]],

        [[ 0.6308],
         [ 0.1362]],

        [[ 0.2039],
         [ 0.6296]],

        [[ 0.6349],
         [ 0.4252]],

        [[ 0.4524],
         [ 0.5

In [453]:
lnk_children

tensor([[[3.5240],
         [3.5610]],

        [[3.5650],
         [3.5281]],

        [[3.5281],
         [3.5322]],

        [[3.5281],
         [3.5281]],

        [[3.5650],
         [3.5650]],

        [[3.5650],
         [3.5322]],

        [[3.4941],
         [3.5281]],

        [[3.5322],
         [3.5610]],

        [[3.5322],
         [3.5322]],

        [[3.5650],
         [3.5650]],

        [[3.5322],
         [3.5322]],

        [[3.5322],
         [3.5281]],

        [[3.5610],
         [3.4632]],

        [[3.5281],
         [3.5610]],

        [[3.5968],
         [3.5968]],

        [[3.5650],
         [3.5322]],

        [[3.5322],
         [3.4632]],

        [[3.5610],
         [3.5650]],

        [[3.5650],
         [3.5650]],

        [[3.5610],
         [3.5968]],

        [[3.5968],
         [3.5852]],

        [[3.5610],
         [3.5650]],

        [[3.5929],
         [3.5891]],

        [[3.5610],
         [3.4632]],

        [[3.5281],
         [3.5281]],

